services:
  - type: web
    name: smart-travel-planner
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py
    envVars:
      - key: GROQ_API_KEY
        value: your_default_key_or_leave_blank
